name: alignment
channels:
  - conda-forge
  - bioconda
dependencies:
  - fontconfig > 2 
  - font-ttf-dejavu-sans-mono > 2
  - multiqc=1.7
  - qualimap=2.2.2b
  - samtools=1.9
  - sambamba=0.6.8
  - samblaster=0.1.24
  - bwa=0.7.17
  - bwakit=0.7.15
  - gatk4=4.0.12.0
  - r-ggplot2=3.1.0
